PythonProject/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.views.static import serve  # 需要导入
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('media/', serve, {'document_root': settings.MEDIA_ROOT}),  # 这部分很重要
    path('BookType/', include('apps.BookType.urls', namespace='BookType')),  # 图书类别模块
    path('Book/', include('apps.Book.urls', namespace='Book')),  # 图书模块
    path('', include("apps.Index.urls", namespace="Index")),  # 首页模块
    # url(r'^tinymce/', include('tinymce.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

apps/Book/urls.py
from apps.Book.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView,FrontAllView
from django.urls import path, re_path

# 正在部署的应用的名称
app_name = 'Book'

urlpatterns = [
    path('frontList/', FrontListView.as_view(), name='frontList'),  # 前台图书查询列表
    path('frontAdd/', FrontAddView.as_view(), name='frontAdd'),  # 前台图书添加
    path('frontAll/', FrontAllView.as_view(), name='frontAll'),
    path('frontShow/<str:barcode>/', FrontShowView.as_view(), name='frontShow'),  # 前台显示图片详情页
    path('update/<int:barcode>/', UpdateView.as_view(), name='update_book'),  # Ajax方式图书更新
    # path('^add$', AddView.as_view(), name='add'),  # 后台添加图书
    # url(r'^backModify/(?P<barcode>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新图书
    # url(r'^list$', ListView.as_view(), name='list'),  # 后台图书列表
    path('deletes/', DeletesView.as_view(), name="delete_books"),  # 删除图书信息
    # url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出图书信息到excel并下载
]

apps/Index/urls.py
from django.urls import path, re_path
# from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView
from apps.Index.views import IndexView,AdminView,LoginView
# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    path(r'', IndexView.as_view(), name='index'),  # 首页
    # url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    path(r'adminView/', AdminView.as_view(), name='adminView'),  # 管理中心
    # url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    path(r'login/', LoginView.as_view(), name="login"),  # 后台登录
    # url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    # url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword'),  # 管理员修改密码
]

apps/Book/models.py
from django.db import models
from apps.BookType.models import BookType
from tinymce.models import HTMLField


class Book(models.Model):
    barcode = models.CharField(max_length=20, default='', primary_key=True, verbose_name='图书条形码')
    bookName = models.CharField(max_length=20, default='', verbose_name='图书名称')
    bookTypeObj = models.ForeignKey(BookType,  db_column='bookTypeObj', on_delete=models.CASCADE, verbose_name='图书类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='图书价格')
    count = models.IntegerField(default=0,verbose_name='图书库存')
    publishDate = models.CharField(max_length=20, default='', verbose_name='出版日期')
    publish = models.CharField(max_length=20, default='', verbose_name='出版社')
    bookPhoto = models.ImageField(upload_to="img", max_length='80', verbose_name='图书图片')  #指定文件保存的路径名 系统自动创建
    bookDesc = HTMLField(verbose_name='图书简介')
    bookFile = models.FileField(upload_to='file', max_length='100', verbose_name='图书文件')

    class Meta:
        db_table = 't_Book'
        verbose_name = '图书信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        book = {
            "barcode": self.barcode,
            "bookName": self.bookName,
            'bookTypeObj': self.bookTypeObj.bookTypeName,
            'bookTypeObjPri': self.bookTypeObj.bookTypeId,
            'price': self.price,
            'count': self.count,
            'publishDate': self.publishDate,
            'publish': self.publish,
            'bookPhoto': self.bookPhoto.url,
            'bookDesc': self.bookDesc,
            'bookFile': self.bookFile.url
        }
        return book

apps/Book/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render, HttpResponse
from django.core.paginator import Paginator
from apps.Book.models import Book
from apps.BookType.models import BookType
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os
from django.utils.decorators import method_decorator
from apps.Index.views import *


class FrontAddView(BaseView):  # 前台图书添加
    def primaryKeyExist(self, barcode):  # 判断主键是否存在
        try:
            Book.objects.get(barcode=barcode)
            return True
        except Book.DoesNotExist:
            return False

    def get(self, request):
        bookTypes = BookType.objects.all()  # 获取所有图书 类型
        context = {
            'bookTypes': bookTypes,
        }
        # 使用模板
        return render(request, 'Book/book_frontAdd.html', context)

    def post(self, request):
        barcode = request.POST.get('book.barcode')  # 判断图书条形码是否存在
        if self.primaryKeyExist(barcode):
            return JsonResponse({'success': False, 'message': '图书条形码已经存在'})

        book = Book()  # 新建一个图书对象然后获取参数
        book.barcode = barcode
        book.bookName = request.POST.get('book.bookName')
        book.bookTypeObj = BookType.objects.get(bookTypeId=int(request.POST.get('book.bookTypeObj.bookTypeId')))
        book.price = float(request.POST.get('book.price'))
        book.count = int(request.POST.get('book.count'))
        book.publishDate = request.POST.get('book.publishDate')
        book.publish = request.POST.get('book.publish')
        try:
            book.bookPhoto = self.uploadImageFile(request, 'book.bookPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        book.bookDesc = request.POST.get('book.bookDesc')
        book.bookFile = self.uploadCommonFile(request, 'book.bookFile')
        book.save()  # 保存图书信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改图书
    def get(self, request, barcode):
        context = {"barcode": barcode}
        return render(request, 'Book/book_frontModify.html', context)


class FrontAllView(BaseView):
    def get(self, request):
        return self.handle(request)

    def handle(self, request):
        # print("1")
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        barcode = ''
        bookName = ''
        publishDate = ''
        bookTypeObj_bookTypeId = '0'
        # print("2")
        # print(barcode, bookName, publishDate, bookTypeObj_bookTypeId)
        # 然后条件组合查询过滤
        book = Book.objects.all().order_by('barcode')
        if barcode != '':
            book = book.filter(barcode__contains=barcode)
        if bookName != '':
            book = book.filter(bookName__contains=bookName)
        if publishDate != '':
            book = book.filter(publishDate__contains=publishDate)
        if bookTypeObj_bookTypeId != '0':
            book = book.filter(bookTypeObj=bookTypeObj_bookTypeId)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(book, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        books_page = self.paginator.page(self.currentPage)

        # 获取所有图书类型
        bookTypes = BookType.objects.all()
        # 构造模板需要的参数
        context = {
            'bookTypes': bookTypes,
            'books_page': books_page,
            'barcode': barcode,
            'bookName': bookName,
            'publishDate': publishDate,
            'bookTypeObj_bookTypeId': int(bookTypeObj_bookTypeId),
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        print(self.currentPage)
        return render(request, 'Book/book_all.html', context)


class FrontListView(BaseView):  # 前台图书查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        barcode = self.getStrParam(request, 'barcode')
        bookName = self.getStrParam(request, 'bookName')
        publishDate = self.getStrParam(request, 'publishDate')
        bookTypeObj_bookTypeId = self.getIntParam(request, 'bookTypeObj.bookTypeId')

        # print(barcode, bookName, publishDate, bookTypeObj_bookTypeId)
        # 然后条件组合查询过滤
        book = Book.objects.all().order_by("barcode")
        if barcode != '':
            book = book.filter(barcode__contains=barcode)
        if bookName != '':
            book = book.filter(bookName__contains=bookName)
        if publishDate != '':
            book = book.filter(publishDate__contains=publishDate)
        if bookTypeObj_bookTypeId != '0':
            book = book.filter(bookTypeObj=bookTypeObj_bookTypeId)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(book, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        books_page = self.paginator.page(self.currentPage)

        # 获取所有图书类型
        bookTypes = BookType.objects.all()
        print(bookTypes)
        print(books_page)
        # 构造模板需要的参数
        context = {
            'bookTypes': bookTypes,
            'books_page': books_page,
            'barcode': barcode,
            'bookName': bookName,
            'publishDate': publishDate,
            'bookTypeObj_bookTypeId': int(bookTypeObj_bookTypeId),
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList
        }
        print("Current Page:", self.currentPage)
        print("Page Size:", self.pageSize)
        # 渲染模板界面
        return render(request, 'Book/book_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示图片详情页
    def get(self, request, barcode):
        bookTypes = BookType.objects.all()
        # 查询需要显示的图书对象
        book = Book.objects.get(barcode=barcode)
        context = {
            'bookTypes': bookTypes,
            'book': book
        }
        # 渲染模板显示
        print(context)
        return render(request, 'Book/book_frontshow.html', context)


class UpdateView(View):
    def get(self, request, barcode):
        # 获取图书对象并渲染更新页面
        book = Book.objects.get(barcode=barcode)
        bookTypes = BookType.objects.all()  # 获取所有图书类别
        context = {
            'bookTypes': bookTypes,
            'book': book
        }
        return render(request, 'Book/book_update.html', context)

    def post(self, request, barcode):
        # 更新图书信息
        book = Book.objects.get(barcode=barcode)
        book.bookName = request.POST.get('book.bookName')
        book.bookTypeObj = BookType.objects.get(bookTypeId=int(request.POST.get('book.bookTypeObj.bookTypeId')))
        book.price = float(request.POST.get('book.price'))
        book.count = int(request.POST.get('book.count'))
        book.publishDate = request.POST.get('book.publishDate')
        book.publish = request.POST.get('book.publish')

        # 处理图书图片上传
        if 'book.bookPhoto' in request.FILES:
            try:
                bookPhotoName = self.uploadImageFile(request, 'book.bookPhoto')
                if bookPhotoName != 'img/NoImage.jpg':
                    book.bookPhoto = bookPhotoName
            except ImageFormatException as ife:
                return render(request, 'update_book.html', {
                    'book': book,
                    'bookTypes': BookType.objects.all(),
                    'error': ife.error
                })

        # 更新图书描述
        book.bookDesc = request.POST.get('book.bookDesc')

        # 处理图书文件上传
        if 'book.bookFile' in request.FILES:
            bookFileName = self.uploadCommonFile(request, 'book.bookFile')
            if bookFileName != 'file/NoFile.jpg':
                book.bookFile = bookFileName

        book.save()
        return redirect('Book:frontList')  # 更新成功后重定向到图书列表页面

    def uploadImageFile(self, request, field_name):
        # 自定义图片上传处理逻辑
        image = request.FILES[field_name]
        # 进行格式检查和存储
        return image.name  # 示例，实际需要保存到文件系统

    def uploadCommonFile(self, request, field_name):
        # 自定义文件上传处理逻辑
        file = request.FILES[field_name]
        # 进行格式检查和存储
        return file.name  # 示例，实际需要保存到文件系统


class AddView(BaseView):  # 后台添加图书
    def primaryKeyExist(self, barcode):  # 判断主键是否存在
        try:
            Book.objects.get(barcode=barcode)
            return True
        except Book.DoesNotExist:
            return False

    def get(self, request):
        # 获取所有图书类型
        bookTypes = BookType.objects.all()
        context = {
            'bookTypes': bookTypes,
        }
        # 渲染显示模板界面
        return render(request, 'Book/book_add.html', context)

    def post(self, request):
        # POST方式处理图书添加业务
        barcode = request.POST.get('book.barcode')
        if self.primaryKeyExist(barcode):
            return JsonResponse({'success': False, 'message': '图书条形码已经存在'})
        # 新建一个图书对象然后收集图书参数
        book = Book()
        book.barcode = barcode
        book.bookName = request.POST.get('book.bookName')
        book.bookTypeObj = BookType.objects.get(bookTypeId=int(request.POST.get('book.bookTypeObj.bookTypeId')))
        book.price = float(request.POST.get('book.price'))
        book.count = int(request.POST.get('book.count'))
        book.publishDate = request.POST.get('book.publishDate')
        book.publish = request.POST.get('book.publish')
        try:

templates/Book/book_all.html
{#{% load staticfiles %}#}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>图书查询</title>
    <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/head.css' %}" rel="stylesheet">
    <link rel="icon" href="https://image.youis.top/00.png" sizes="32x32">
    <link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
    {% include 'header.html' %}

    <div class="col-md-9 wow fadeInRight">
        <div class="row">
            {% for book in books_page %}
                {% if forloop.counter|add:-1|divisibleby:4 %}
                    <div class="col-md-3 bottom15" style="clear: left;">
                {% else %}
                    <div class="col-md-3 bottom15">
                {% endif %}
            <a href="#"><img class="img-responsive" src="{{ book.bookPhoto.url }}"/></a>
            <div class="showFields">
                <div class="field">
                    图书条形码:{{ book.barcode }}
                </div>
                <div class="field">
                    图书名称:{{ book.bookName }}
                </div>
                <div class="field">
                    图书所在类别:{{ book.bookTypeObj.bookTypeName }}
                </div>
                <div class="field">
                    图书价格:{{ book.price }}
                </div>
                <div class="field">
                    库存:{{ book.count }}
                </div>
                <div class="field">
                    出版日期:{{ book.publishDate }}
                </div>
                <div class="field">
                    出版社:{{ book.publish }}
                </div>
                <div class="field">
                    图书文件:
                    {% if book.bookFile == 'file/NoFile.jpg' %}
                        暂无文件
                    {% else %}
                        <a href='{{ book.bookFile.url }}' target='_blank'>{{ book.bookFile }}</a>
                    {% endif %}
                </div>
                <a class="btn  btn-info top5" href="{% url 'Book:frontShow' book.barcode %}">详情</a>
                <a class="btn  btn-info top5" href="{% url 'Book:update_book' book.barcode %}">修改</a>
                <a class="btn  btn-info top5" onclick="bookDelete('{{ book.barcode }}');">删除</a>
            </div>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
<div id="editModal" style="display:none;">
    <form id="updateForm" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" id="editBarcode" name="barcode">

        <div>
            <label for="bookName">图书名称:</label>
            <input type="text" id="bookName" name="book.bookName" required>
        </div>

        <div>
            <label for="bookTypeObj">图书类别:</label>
            <select id="bookTypeObj" name="book.bookTypeObj.bookTypeId" required>
                <!-- 这里可以动态填充书籍类型 -->
                {% for bookType in bookTypes %}
                    <option value="{{ bookType.bookTypeId }}">{{ bookType.bookTypeName }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="price">价格:</label>
            <input type="number" id="price" name="book.price" step="0.01" required>
        </div>

        <div>
            <label for="count">库存:</label>
            <input type="number" id="count" name="book.count" required>
        </div>

        <div>
            <label for="publishDate">出版日期:</label>
            <input type="date" id="publishDate" name="book.publishDate" required>
        </div>

        <div>
            <label for="publish">出版社:</label>
            <input type="text" id="publish" name="book.publish" required>
        </div>

        <div>
            <label for="bookDesc">图书简介:</label>
            <textarea id="bookDesc" name="book.bookDesc"></textarea>
        </div>

        <div>
            <label for="bookPhoto">图书图片:</label>
            <input type="file" id="bookPhoto" name="book.bookPhoto">
            <p>当前图片: <img id="currentBookPhoto" src="" style="max-width: 100px;" alt="当前图书图片"></p>
        </div>

        <div>
            <label for="bookFile">图书文件:</label>
            <input type="file" id="bookFile" name="book.bookFile">
            <p>当前文件: <a id="currentBookFile" href="#" target="_blank">无文件</a></p>
        </div>

        <button type="submit">保存</button>
    </form>
</div>
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
<script>
    function bookEdit(barcode) {
        // 获取图书信息
        $.ajax({
            url: '/Book/update/' + barcode + '/',
            type: 'GET',
            success: function(data) {
            // 填充表单字段
            $('#editBarcode').val(data.barcode);
            $('#bookName').val(data.bookName);
            $('#price').val(data.price);
            $('#count').val(data.count);
            $('#publishDate').val(data.publishDate);
            $('#publish').val(data.publish);
            $('#bookDesc').val(data.bookDesc);
            $('#currentBookPhoto').attr('src', data.bookPhoto);
            $('#currentBookFile').attr('href', data.bookFile).text(data.bookFile.split('/').pop());

            // 填充图书类别
            $('#bookTypeObj').val(data.bookTypeObjPri);

            // 显示编辑表单
            $('#editModal').show();
        },
        error: function(xhr, status, error) {
            console.error('获取图书数据失败:', error);
        }
    });

        // 处理表单提交
        $('#updateForm').off('submit').on('submit', function(event) {
            event.preventDefault();
            var formData = new FormData(this);
            $.ajax({
                url: '/Book/update/' + barcode + '/',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function(response) {
                    if (response.success) {
                        alert('保存成功');
                        // 重新加载页面或更新表单
                    } else {
                        alert('保存失败: ' + response.message);
                    }
                },
                error: function(xhr, status, error) {
                    console.error('更新失败:', xhr.responseText);
                    alert("更新失败" + xhr.responseText);
                }
            });
        });
    }

    $(function () {
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function () {
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();

        /*出版日期组件*/
        $('.book_publishDate_edit').datetimepicker({
            language: 'zh-CN',  //语言
            format: 'yyyy-mm-dd',
            minView: 2,
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            minuteStep: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0
        });
    })
    function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

    const csrftoken = getCookie('csrftoken');
    function bookDelete(barcodes) {
    if (confirm('确定要删除这些书吗？')) {
        $.ajax({
            url: '/Book/deletes/',
            type: 'POST',
            headers: {
                'X-CSRFToken': csrftoken // 确保 CSRF token 正确
            },
            data: {
                barcodes: barcodes // 以逗号分隔的条形码字符串
            },
            success: function(response) {
                if (response.success) {
                    alert(response.message);
                    // 刷新页面或更新界面
                } else {
                    alert('删除失败: ' + response.message);
                }
            },
            error: function(xhr) {
                console.error('删除失败:', xhr);
            }
        });
    }
}
</script>
</body>
</html>

templates/Book/book_update.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>更新图书信息</title>
    <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
    <link rel="icon" href="https://image.youis.top/00.png" sizes="32x32">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
    <ul class="breadcrumb">
        <li><a href="{% url 'Index:index' %}">首页</a></li>
        <li><a href="{% url 'Book:frontList' %}">图书信息</a></li>
        <li class="active">更新图书信息</li>
    </ul>
    <form action="{% url 'Book:update_book' book.barcode %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">图书条形码:</div>
            <div class="col-md-10 col-xs-6">{{ book.barcode }}</div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">图书名称:</div>
            <div class="col-md-10 col-xs-6">
                <input type="text" name="book.bookName" value="{{ book.bookName }}" class="form-control" required>
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">图书所在类别:</div>
            <div class="col-md-10 col-xs-6">
                <select name="book.bookTypeObj.bookTypeId" class="form-control" required>
                    {% for type in bookTypes %}
                        <option value="{{ type.bookTypeId }}" {% if type.bookTypeId == book.bookTypeObj.bookTypeId %}selected{% endif %}>{{ type.bookTypeName }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">图书价格:</div>
            <div class="col-md-10 col-xs-6">
                <input type="number" step="0.01" name="book.price" value="{{ book.price }}" class="form-control" required>
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">库存:</div>
            <div class="col-md-10 col-xs-6">
                <input type="number" name="book.count" value="{{ book.count }}" class="form-control" required>
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">出版日期:</div>
            <div class="col-md-10 col-xs-6">
                <input type="date" name="book.publishDate" value="{{ book.publishDate }}" class="form-control" required>
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">出版社:</div>
            <div class="col-md-10 col-xs-6">
                <input type="text" name="book.publish" value="{{ book.publish }}" class="form-control" required>
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">图书图片:</div>
            <div class="col-md-10 col-xs-6">
                <input type="file" name="book.bookPhoto" class="form-control">
                <img class="img-responsive" src="{{ book.bookPhoto.url }}" alt="图书图片" style="margin-top: 10px; max-height: 200px;"/>
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">图书简介:</div>
            <div class="col-md-10 col-xs-6">
                <textarea name="book.bookDesc" class="form-control" rows="5" required>{{ book.bookDesc }}</textarea>
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4 text-right bold">图书文件:</div>
            <div class="col-md-10 col-xs-6">
                <input type="file" name="book.bookFile" class="form-control">
                {% if book.bookFile != 'file/NoFile.jpg' %}
                    <p><a href="{{ book.bookFile.url }}" target="_blank">下载当前文件</a></p>
                {% endif %}
            </div>
        </div>
        <div class="row bottom15">
            <div class="col-md-2 col-xs-4"></div>
            <div class="col-md-6 col-xs-6">
                <button type="submit" class="btn btn-success">保存</button>
                <button type="button" onclick="history.back();" class="btn btn-info">返回</button>
            </div>
        </div>
    </form>
</div>
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
    $(function () {
        new WOW().init();
    });
</script>
</body>
</html>