PythonProject/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.views.static import serve  # 需要导入
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('media/', serve, {'document_root': settings.MEDIA_ROOT}),  # 这部分很重要
    path('BookType/', include('apps.BookType.urls', namespace='BookType')),  # 图书类别模块
    path('Book/', include('apps.Book.urls', namespace='Book')),  # 图书模块
    path('', include("apps.Index.urls", namespace="Index")),  # 首页模块
    # url(r'^tinymce/', include('tinymce.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

apps/BookType/urls.py
from apps.BookType.views import FrontAddView, FrontListView, ListAllView, FrontEditView, FrontDeleteView
from django.urls import path, re_path

# 正在部署的应用的名称
app_name = 'BookType'

urlpatterns = [
    path(r'frontAdd', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    path(r'frontList', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    path(r'listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有图书类型
    path(r'frontEdit', FrontEditView.as_view(), name='frontEdit'),  # 前台修改
    path(r'frontDelete', FrontDeleteView.as_view(), name='frontDelete'),  # 前台删除
]

apps/Index/urls.py
from django.urls import path, re_path
# from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView
from apps.Index.views import IndexView,AdminView,LoginView
# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    path(r'', IndexView.as_view(), name='index'),  # 首页
    # url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    path(r'adminView/', AdminView.as_view(), name='adminView'),  # 管理中心
    # url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    path(r'login/', LoginView.as_view(), name="login"),  # 后台登录
    # url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    # url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword'),  # 管理员修改密码
]

apps/BookType/models.py
from django.db import models


class BookType(models.Model):
    bookTypeId = models.AutoField(primary_key=True, verbose_name='图书类型id')
    bookTypeName = models.CharField(max_length=40, default='', verbose_name='图书类型名称')
    days = models.IntegerField(default=0, verbose_name='可借阅天数')

    class Meta:
        db_table = 't_BookType'
        verbose_name = '图书类别'
        verbose_name_plural = verbose_name

apps/BookType/views.py
from django.views.generic import View
from django.shortcuts import render
from apps.BookType.models import BookType
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect


class FrontAddView(View):
    def get(self, request):
        return render(request, 'BookType/bookType_add.html')

    def post(self, request):
        print("添加图书类型************************")
        id = request.POST.get("bookType_Id")
        name = request.POST.get("bookType_Name")
        day = request.POST.get("bookType_Day")

        try:
            # 如果 bookTypeId 是由外部提供的，并且你想用它作为主键，请确保它是唯一的
            # 如果不是主键，只是一个普通字段，并且你想保留外部提供的值，那么可以保留这行代码
            # 但通常，主键应该由数据库自动管理（如使用 AutoField）
            # 这里我假设 bookTypeId 不是一个主键，并且你想保留它
            book_type = BookType.objects.create(bookTypeId=id, bookTypeName=name, days=day)
            print("图书类型添加成功:", book_type)
            return redirect("BookType:frontList")
        except Exception as e:
            # 捕获所有异常，但最好捕获具体的异常类型以进行更精确的处理
            print("添加图书类型时发生错误:", e)
            # 可以记录日志、发送错误通知等
            # 返回给用户一个友好的错误页面
            return HttpResponse("添加图书类型时发生错误，请检查图书类型ID，它应该唯一。", status=500)


class ListAllView(View):
    def get(self, request):
        bookTypes = BookType.objects.all()
        bookTypeList = []
        for bookType in bookTypes:
            bookTypeObj = {
                'bookTypeId': bookType.bookTypeId,
                'bookTypeName': bookType.bookTypeName,
            }
            bookTypeList.append(bookTypeObj)
        return JsonResponse(bookTypeList, safe=False)


class FrontEditView(View):
    def get(self, request):
        type_Id = request.GET.get("type_Id")
        type_Name = request.GET.get("type_Name")
        type_Day = request.GET.get("type_Day")
        return render(request, "BookType/bookType_edit.html",
                      {"bookType_Id": type_Id, "bookType_Name": type_Name, "bookType_Day": type_Day})

    def post(self, request):
        id = request.POST.get("bookType_Id")
        name = request.POST.get("bookType_Name")
        day = request.POST.get("bookType_Day")
        print(id, name, day)
        result = BookType.objects.filter(bookTypeId=id).update(bookTypeId=id, bookTypeName=name, days=day)
        print(id, name, day)
        return redirect("BookType:frontList")


class FrontDeleteView(View):
    def get(self, request):
        type_Id = request.GET.get("type_Id")
        BookType.objects.filter(bookTypeId=type_Id).delete()
        return redirect("BookType:frontList")


class FrontListView(View):
    def get(self, request):
        pageSize = 5
        currentPage = request.GET.get("currentPage")
        bookTypes = BookType.objects.all()
        paginator = Paginator(bookTypes, pageSize)
        totalPage = paginator.num_pages
        recordNumber = paginator.count

        # 获取第page页的内容
        try:
            currentPage = int(currentPage)
        except Exception as e:
            currentPage = 1
        if currentPage > totalPage:
            currentPage = totalPage

        # 获取第page页的Page实例对象
        bookTypes_page = paginator.page(currentPage)

        startIndex = (currentPage - 1) * pageSize  # 计算起始序号

        startPage = currentPage - 5
        endPage = currentPage + 5
        if startPage < 1:
            startPage = 1
        if endPage > totalPage:
            endPage = totalPage;

        pageList = list(range(startPage, endPage + 1))

        context = {
            'bookTypes_page': bookTypes_page,
            'currentPage': currentPage,
            'totalPage': totalPage,
            'recordNumber': recordNumber,
            'startIndex': startIndex,
            'pageList': pageList,
        }

        print(pageList)

        # 使用模板
        return render(request, 'BookType/bookType_frontquery_result.html', context)

    def post(self, request):
        pass

templates/BookType/bookType_add.html
{#{% load staticfiles %}#}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>图书类型查询</title>
    <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
    <link rel="icon" href="https://image.youis.top/00.png" sizes="32x32">
    <link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/head.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;">
<div class="container">
    {% include 'header.html' %}
    <div class="row">
        <div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li><a href="{% url 'Index:index' %}">首页</a></li>
                    <li role="presentation" class="active"><a href="#bookTypeListPanel"
                                                              aria-controls="bookTypeListPanel" role="tab"
                                                              data-toggle="tab">图书类型列表</a></li>
                    <li role="presentation"><a href="{% url 'BookType:frontAdd' %}">添加图书类型</a></li>
                </ul>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <form class="form-horizontal" name="bookAddForm" id="bookAddForm" enctype="multipart/form-data"
                          method="post" class="mar_t15">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="book_barcode" class="col-md-2 text-right">图书类型ID:</label>
                            <div class="col-md-8">
                                <input type="text" name="bookType_Id" class="form-control" placeholder="图书类型ID">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="book_bookName" class="col-md-2 text-right">图书类型名称:</label>
                            <div class="col-md-8">
                                <input type="text" name="bookType_Name" class="form-control" placeholder="图书类型名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="book_bookName" class="col-md-2 text-right">可借天数:</label>
                            <div class="col-md-8">
                                <input type="text" name="bookType_Day" class="form-control" placeholder="可借天数">
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-2"></span>
                            <input type="submit" value="添加" class="btn btn-info bottom5 top5">
                            <input type="button" id="Exit"
                                   onclick="javascrtpt:window.location.href='{% url  "BookType:frontList" %} '"
                                   value="取消" class="btn btn-info bottom5 top5">
                        </div>
                        <style>#bookAddForm .form-group {
                            margin: 5px;
                        }  </style>
                    </form>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
</body>
</html>

templates/BookType/bookType_edit.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>图书类型查询</title>
    <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
    <link rel="icon" href="https://image.youis.top/00.png" sizes="32x32">
    <link href="{% static 'css/head.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
    {% include 'header.html' %}
    <div class="row">
        <div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li><a href="{% url 'Index:index' %}">首页</a></li>
                    <li role="presentation" class="active"><a href="#bookTypeListPanel"
                                                              aria-controls="bookTypeListPanel" role="tab"
                                                              data-toggle="tab">图书类型列表</a></li>
                    <li role="presentation"><a href="{% url 'BookType:frontAdd' %}">添加图书类型</a></li>
                </ul>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <form class="form-horizontal" name="bookAddForm" id="bookAddForm" enctype="multipart/form-data"
                          method="post" class="mar_t15">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="book_barcode" class="col-md-2 text-right">图书类型ID:</label>
                            <div class="col-md-8">
                                <input type="text" name="bookType_Id" value="{{ bookType_Id }}" readonly="readonly"
                                       class="form-control" placeholder="图书类型ID">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="book_bookName" class="col-md-2 text-right">图书类型名称:</label>
                            <div class="col-md-8">
                                <input type="text" name="bookType_Name" value="{{ bookType_Name }}" class="form-control"
                                       placeholder="图书类型名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="book_bookName" class="col-md-2 text-right">可借天数:</label>
                            <div class="col-md-8">
                                <input type="text" name="bookType_Day" value="{{ bookType_Day }}" class="form-control"
                                       placeholder="可借天数">
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-2"></span>
                            <input type="submit" value="更新" class="btn btn-primary bottom5 top5">
                            <input type="button" id="Exit"
                                   onclick="javascrtpt:window.location.href='{% url  "BookType:frontList" %} '"
                                   value="取消" class="btn btn-primary bottom5 top5">
                        </div>
                        <style>#bookAddForm .form-group {
                            margin: 5px;
                        }  </style>
                    </form>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
    {#$(function(){#}
    {#    $('#Exit').click(function(){#}
    {##}
    {#    })#}
</script>
</body>
</html>

templates/BookType/bookType_frontquery_result.html
{#{% load staticfiles %}#}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>图书类型查询</title>
    <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
    <link rel="icon" href="https://image.youis.top/00.png" sizes="32x32">
    <link href="{% static 'css/head.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
    {% include 'header.html' %}
    <div class="row">
        <div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li><a href="{% url 'Index:index' %}">首页</a></li>
                    <li role="presentation" class="active"><a href="#bookTypeListPanel"
                                                              aria-controls="bookTypeListPanel" role="tab"
                                                              data-toggle="tab">图书类型列表</a></li>
                    <li role="presentation"><a href="{% url 'BookType:frontAdd' %}">添加图书类型</a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="bookTypeListPanel">
                        <div class="row">
                            <div class="col-md-12 top5">
                                <div class="table-responsive">
                                    <table class="table table-condensed table-hover">
                                        <tr class="success bold">
                                            <td>序号</td>
                                            <td>图书类别</td>
                                            <td>类别名称</td>
                                            <td>可借阅天数</td>
                                            <td>操作1</td>
                                            <td>操作2</td>
                                        </tr>
                                        {% for bookType in bookTypes_page %}
                                            <tr>
                                                <td>{{ startIndex|add:forloop.counter }}</td>
                                                <td>{{ bookType.bookTypeId }}</td>
                                                <td>{{ bookType.bookTypeName }}</td>
                                                <td>{{ bookType.days }}</td>
                                                <td>
                                                    <a href="{% url 'BookType:frontEdit' %}?type_Id={{ bookType.bookTypeId }}&&type_Name={{ bookType.bookTypeName }}&&type_Day={{ bookType.days }}">修改</a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'BookType:frontDelete' %}?type_Id={{ bookType.bookTypeId }}">删除</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
</body>
</html>