PythonProject/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.views.static import serve  # 需要导入
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('media/', serve, {'document_root': settings.MEDIA_ROOT}),  # 这部分很重要
    path('BookType/', include('apps.BookType.urls', namespace='BookType')),  # 图书类别模块
    path('Book/', include('apps.Book.urls', namespace='Book')),  # 图书模块
    path('', include("apps.Index.urls", namespace="Index")),  # 首页模块
    # url(r'^tinymce/', include('tinymce.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

apps/Book/urls.py
from apps.Book.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView,FrontAllView
from django.urls import path, re_path

# 正在部署的应用的名称
app_name = 'Book'

urlpatterns = [
    path('frontList/', FrontListView.as_view(), name='frontList'),  # 前台图书查询列表
    path('frontAdd/', FrontAddView.as_view(), name='frontAdd'),  # 前台图书添加
    path('frontAll/', FrontAllView.as_view(), name='frontAll'),
    path('frontShow/<str:barcode>/', FrontShowView.as_view(), name='frontShow'),  # 前台显示图片详情页
    path('update/<int:barcode>/', UpdateView.as_view(), name='update_book'),  # Ajax方式图书更新
    # path('^add$', AddView.as_view(), name='add'),  # 后台添加图书
    # url(r'^backModify/(?P<barcode>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新图书
    # url(r'^list$', ListView.as_view(), name='list'),  # 后台图书列表
    path('deletes/', DeletesView.as_view(), name="delete_books"),  # 删除图书信息
    # url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出图书信息到excel并下载
]

apps/Index/urls.py
from django.urls import path, re_path
# from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView
from apps.Index.views import IndexView,AdminView,LoginView
# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    path(r'', IndexView.as_view(), name='index'),  # 首页
    # url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    path(r'adminView/', AdminView.as_view(), name='adminView'),  # 管理中心
    # url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    path(r'login/', LoginView.as_view(), name="login"),  # 后台登录
    # url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    # url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword'),  # 管理员修改密码
]

templates/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>管理中心</title>
    <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
    <link rel="icon" href="https://image.youis.top/00.png" sizes="32x32">
    <link href="{% static 'css/head.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body>
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="bookTypeListPanel">
        <div class="row">
            <div class="col-md-12 top5">
                <div class="table-responsive">
                    <table class="table table-condensed table-hover">
                        <tr class="success bold">
                            <td>序号</td>
                            <td>条形码</td>
                            <td>书名</td>
                            <td>出版社</td>
                            <td>价格</td>
                            <td>数量</td>
                            <td>出版日期</td>
                        </tr>
                        {% for book in result %}
                            <tr>
                                <td>{{ startIndex|add:forloop.counter }}</td>
                                <td>{{ book.barcode }}</td>
                                <td>{{ book.bookName }}</td>
                                <td>{{ book.publish }}</td>
                                <td>{{ book.price }}</td>
                                <td>{{ book.count }}</td>
                                <td>{{ book.publishDate }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div align="center">
    <input type="button" id="savaBtn" class="btn  btn-info top5" value="导出所有纪录" style="position: center">
    <a href="{% url 'Index:index' %}" class="btn  btn-info top5">返回主页</a>
</div>
</body>

<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
<script>

</script>
</html>

templates/header.html
<!--导航开始-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-headBigText-->
            <a href="{% url 'Index:index' %}" class="navbar-brand">图书查询网</a>
        </div>
        <!--导航-->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'Index:index' %}" style="color:grey">首页</a></li>
                <li><a href="{% url 'Book:frontAll' %}" style="color:grey">所有图书</a></li>
                <li><a href="{% url 'BookType:frontList' %}" style="color:grey">图书类型</a></li>
                <li><a href="{% url 'Book:frontList' %}" style="color:grey">图书查询</a></li>
<!--                <li><a href="{% url 'Index:login' %}">登录</a></li>-->
<!--                <li><a href="#">退出</a></li>-->
            </ul>
            <!--
            <ul class="nav navbar-nav navbar-right">
                <li><a href="">登录</a></li>
                <li><a href="#">退出</a></li>
            </ul>
            -->
        </div>
        <!--导航-->
    </div>
</nav>
<!--导航结束-->
{% csrf_token %}

templates/index.html
{#{% load staticfiles %}#}
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>图书管理系统-首页</title>
    <link rel="icon" href="https://image.youis.top/00.png" sizes="32x32">
    <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
    <link href="{% static 'css/head.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">

    {#   这是主页的页头部分  #}
    {% include 'header.html' %}

    <!-- 用于展示滚动图片 -->
    <section id="main_ad" class="carousel slide" data-ride="carousel">
        <!-- 下面的小点点，活动指示器 -->
        <ol class="carousel-indicators">
            <li data-target="#main_ad" data-slide-to="0" class="active"></li>
            <li data-target="#main_ad" data-slide-to="1"></li>
            <li data-target="#main_ad" data-slide-to="2"></li>
            <li data-target="#main_ad" data-slide-to="3"></li>
            <li data-target="#main_ad" data-slide-to="4"></li>
        </ol>
        <!-- 轮播项 -->
        <div class="carousel-inner" role="listbox">
            <div class="item active" data-image-lg="/static/images/slider/slide_02_2000x410.jpg"></div>
            <div class="item" data-image-lg="{% static 'images/slider/slide_01_2000x410.jpg' %}"></div>
            <div class="item" data-image-lg="{% static 'images/slider/slide_02_2000x410.jpg' %}"></div>
            <div class="item" data-image-lg="{% static 'images/slider/slide_03_2000x410.jpg' %}"></div>
            <div class  ="item" data-image-lg="{% static 'images/slider/slide_04_2000x410.jpg' %}"></div>
            <div class="item" data-image-lg="{% static 'images/slider/slide_05_2000x410.jpg' %}"></div>
        </div>
        <!-- 控制按钮 -->
        <a class="left carousel-control" href="#main_ad" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">上一页</span>
        </a>
        <a class="right carousel-control" href="#main_ad" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">下一页</span>
        </a>
    </section>
    <!-- /展示滚动图片结束 -->

</div>
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/login.html
{#{% load staticfiles %}#}
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>信息管理系统_用户登录</title>
    <link rel="icon" href="https://image.youis.top/00.png" sizes="32x32">
    <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
    <link href="{% static 'css/head.css' %}" rel="stylesheet">
    <link rel='stylesheet' href="{% static 'css/login.css' %}">

</head>
<body>
{#   这是主页的页头部分  #}
{% include 'header.html' %}
<div class="container">
<br>
    <br>
    <br>
    <br>
    <br>
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <form method="post" action="{% url "Index:login" %}" class="form-horizontal">
                <span class="heading">用户登录</span>
                <div class="form-group">
                    <input type="text" class="form-control" id="inputEmail3" name="username" placeholder="用户名或电子邮件">
                    <i class="fa fa-user"></i>
                </div>
                <div class="form-group help">
                    <input type="password" class="form-control" id="inputPassword3" name="password" placeholder="密　码">
                    <i class="fa fa-lock"></i>
                    <a href="#" class="fa fa-question-circle"></a>
                </div>
                {% csrf_token %} <!-验证数据-->
                <div class="form-group">
                    <div class="main-checkbox">
                        <input type="checkbox" value="None" id="checkbox1" name="check"/>
                        <label for="checkbox1"></label>
                    </div>
                    <span class="text">记住账号</span>
                    <input type="submit" class="btn  btn-info top5" value="登录">
                    <span style="color:red;">{{ error_msg }}</span>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'easyui/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'easyui/jquery.easyui.min.js' %}"></script>

</body>
</html>